proper talk links
neurodata/neurodata.io pull request #279
Opened 2019-08-26 18:07 UTC by loftusa

Simplified names to talks, to just be the name of each tool.
Each link is for the slides to talk given on the day the tool was presented during workshop.
`neurodata/talks` repo updates as well to account for new names.

2019-08-26 19:34 UTC, falkben approved these changes

2019-08-26 19:36 UTC, falkben requested changes
Please add daniel tward in acknowledgements to the ardent talk

2019-08-26 19:37 UTC, falkben commented
@DevinCrowley

2019-08-26 20:38 UTC, loftusa commented
FYI, I deleted the old talks links in the `talks` repo as part of the cleanup in preparation for this PR
(although fortunately it looks like the links still work on the website)

2019-08-26 20:51 UTC, falkben commented
> 
> 
> FYI, I deleted the old talks links in the `talks` repo as part of the cleanup in preparation for this PR
> (although fortunately it looks like the links still work on the website)

Please undo those commits until this PR is merged, otherwise those links will break

2019-08-27 15:21 UTC, loftusa commented
> > FYI, I deleted the old talks links in the `talks` repo as part of the cleanup in preparation for this PR
> > (although fortunately it looks like the links still work on the website)
> 
> Please undo those commits until this PR is merged, otherwise those links will break

Ok, old slide names still exist until this is merged.
@DevinCrowley

2019-08-27 15:38 UTC, DevinCrowley commented
Hey @falkben, I added Daniel to the acknowledgements and put the final slide in talks as ardent.pdf, and removed all my other files for compiling the .tex.

2019-08-27 16:26 UTC, falkben commented
> Hey @falkben, I added Daniel to the acknowledgements and put the final slide in talks as ardent.pdf, and removed all my other files for compiling the .tex.

great, make a PR in talks repo.  then we can revisit this PR

2019-08-27 20:27 UTC, falkben approved these changes

2019-08-27 20:27 UTC, merged