Update reg.yaml
neurodata/neurodata.io pull request #287
Opened 2019-09-15 18:34 UTC by DevinCrowley

Add installation tab, update examples link to new location of demo.ipynb, and rewrite main text (details).

2019-09-16 14:32 UTC, falkben requested changes
Getting a 503 error when I try to access examples.  I think that should now link to: https://ardent.neurodata.io/demo/demo.html right?

2019-09-30 16:18 UTC, DevinCrowley commented
That's right

On Mon, Sep 16, 2019 at 10:32 AM Ben Falk <notifications@github.com> wrote:

> *@falkben* requested changes on this pull request.
>
> Getting a 503 error when I try to access examples. I think that should now
> link to: https://ardent.neurodata.io/demo/demo.html right?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/neurodata/neurodata.io/pull/287?email_source=notifications&email_token=AIZAD3KNKPCOZOAE6IPND7DQJ6KHBA5CNFSM4IW3RJXKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCE2MXXY#pullrequestreview-288672735>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AIZAD3I4BZNER4HF6P3PHUDQJ6KHBANCNFSM4IW3RJXA>
> .
>

2019-10-01 03:40 UTC, jovo commented on content/tools/reg.yaml
> +examples: "https://ardent.neurodata.io/demo/demo.html"
this should link here: https://ardent.neurodata.io/tutorial.html

2019-10-01 03:41 UTC, jovo commented on content/tools/reg.yaml
> +examples: "https://ardent.neurodata.io/demo/demo.html"
i'm resolving conversation to approve, but please update link

2019-10-01 17:34 UTC, falkben approved these changes

2019-10-03 14:26 UTC, falkben approved these changes

2019-10-03 14:26 UTC, merged